# Site settings
title: John Wilde
email: johnwilde@gmail.com
description: >
  John Wilde's coding projects 
url: "https://johnwilde.github.io"

# Build settings
markdown: kramdown

collections:
  - changes

plugins:
  - octopress-autoprefixer
  - jekyll-redirect-from

exclude:
  - vendor
